language: node_js
node_js:
  - "6"
script:
  - npm test
before_script:
  - "npm install peerDependency"
after_success:
  - npm run test:coverage
  - cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - rm -rf ./coverage
